[constants]

# Change this for youe specific system
toolchain = '/home/techie-guy/dev/programs/Android_SDK/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin'
api = '30'

[binaries]
c = toolchain / ('aarch64-linux-android' + api + '-clang')
cpp = toolchain / ('aarch64-linux-android' + api + '-clang++')
ar = toolchain / 'llvm-ar'
strip = toolchain / 'llvm-strip'

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'armv8'
endian = 'little'
