# Manually change desktop session
option('linux_windowing', type: 'combo', choices: ['x11', 'wayland'], value: 'wayland')

# Add Android NDK path here
option('ndk_home', type: 'string', value: '/home/techie-guy/dev/programs/Android_SDK/ndk/25.1.8937393')

# Build Sandbox
option('build_sandbox', type: 'boolean', value: true)
