#pragma once

const char* UI_RECT_VERTEX_SHADER = 
    "#version 300 es\n"
    "\n"
    "in vec2 a_pos;\n"
    "in vec4 a_color;\n"
    "in vec2 a_norm_pos;\n"
    "in vec2 a_rect_pos;\n"
    "in vec2 a_rect_size;\n"
    "in vec4 a_corner_radius;\n"
    "in vec4 a_border_width;\n"
    "\n"
    "out vec4 f_color;\n"
    "out vec2 f_norm_pos;\n"
    "out vec2 f_rect_pos;\n"
    "out vec2 f_rect_size;\n"
    "out vec4 f_corner_radius;\n"
    "out vec4 f_border_width;\n"
    "\n"
    "uniform mat4 projection;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = projection * vec4(a_pos, 0.0, 1.0);\n"
    "\n"
    "    f_color = a_color;\n"
    "    f_norm_pos = a_norm_pos;\n"
    "    f_rect_pos = a_rect_pos;\n"
    "    f_rect_size = a_rect_size;\n"
    "    f_corner_radius = a_corner_radius;\n"
    "    f_border_width = a_border_width;\n"
    "}\n";

const char* UI_RECT_FRAGMENT_SHADER = 
    "#version 300 es\n"
    "\n"
    "precision mediump float;\n"
    "\n"
    "in vec4 f_color;\n"
    "in vec2 f_norm_pos;\n"
    "in vec2 f_rect_pos;\n"
    "in vec2 f_rect_size;\n"
    "in vec4 f_corner_radius;\n"
    "in vec4 f_border_width;\n"
    "\n"
    "out vec4 FragColor;\n"
    "\n"
    "uniform sampler2D sampler;\n"
    "uniform bool has_texture;\n"
    "\n"
    "// Used Claude and clay example renderer\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec2 pixel = f_rect_pos + f_norm_pos * f_rect_size;\n"
    "    vec2 local = pixel - f_rect_pos;\n"
    "    float w = f_rect_size.x;\n"
    "    float h = f_rect_size.y;\n"
    "\n"
    "    float tl = f_corner_radius.x;\n"
    "    float tr = f_corner_radius.y;\n"
    "    float bl = f_corner_radius.z;\n"
    "    float br = f_corner_radius.w;\n"
    "\n"
    "    float outer_alpha = 1.0;\n"
    "    if(tl > 0.0 && local.x < tl && local.y < tl)\n"
    "        outer_alpha = step(length(local - vec2(tl, tl)), tl);\n"
    "    if(tr > 0.0 && local.x > w - tr && local.y < tr)\n"
    "        outer_alpha *= step(length(local - vec2(w - tr, tr)), tr);\n"
    "    if(bl > 0.0 && local.x < bl && local.y > h - bl)\n"
    "        outer_alpha *= step(length(local - vec2(bl, h - bl)), bl);\n"
    "    if(br > 0.0 && local.x > w - br && local.y > h - br)\n"
    "        outer_alpha *= step(length(local - vec2(w - br, h - br)), br);\n"
    "\n"
    "    if(outer_alpha < 0.5) discard;\n"
    "\n"
    "    bool has_border = f_border_width.x > 0.0 || f_border_width.y > 0.0 || f_border_width.z > 0.0 || f_border_width.w > 0.0;\n"
    "\n"
    "    if(has_border)\n"
    "    {\n"
    "        float T = f_border_width.x;\n"
    "        float R = f_border_width.y;\n"
    "        float B = f_border_width.z;\n"
    "        float L = f_border_width.w;\n"
    "\n"
    "        float iw = w - L - R;\n"
    "        float ih = h - T - B;\n"
    "        vec2 inner_local = local - vec2(L, T);\n"
    "\n"
    "        float itl = max(tl - min(T, L), 0.0);\n"
    "        float itr = max(tr - min(T, R), 0.0);\n"
    "        float ibl = max(bl - min(B, L), 0.0);\n"
    "        float ibr = max(br - min(B, R), 0.0);\n"
    "\n"
    "        bool inside_inner = true;\n"
    "        if(itl > 0.0 && inner_local.x < itl && inner_local.y < itl)\n"
    "            inside_inner = length(inner_local - vec2(itl, itl)) <= itl;\n"
    "        if(itr > 0.0 && inner_local.x > iw - itr && inner_local.y < itr)\n"
    "            inside_inner = inside_inner && length(inner_local - vec2(iw - itr, itr)) <= itr;\n"
    "        if(ibl > 0.0 && inner_local.x < ibl && inner_local.y > ih - ibl)\n"
    "            inside_inner = inside_inner && length(inner_local - vec2(ibl, ih - ibl)) <= ibl;\n"
    "        if(ibr > 0.0 && inner_local.x > iw - ibr && inner_local.y > ih - ibr)\n"
    "            inside_inner = inside_inner && length(inner_local - vec2(iw - ibr, ih - ibr)) <= ibr;\n"
    "\n"
    "        if(inside_inner && inner_local.x >= 0.0 && inner_local.x <= iw && inner_local.y >= 0.0 && inner_local.y <= ih) discard;\n"
    "    }\n"
    "\n"
    "    if(has_texture)\n"
    "        FragColor = texture(sampler, f_norm_pos) * f_color;\n"
    "    else\n"
    "        FragColor = f_color;\n"
    "}\n";

const char* UI_FONT_VERTEX_SHADER = 
    "#version 300 es\n"
    "\n"
    "in vec2 a_pos;\n"
    "in vec4 a_color;\n"
    "in vec2 a_tex_coord;\n"
    "\n"
    "out vec4 f_color;\n"
    "out vec2 f_tex_coord;\n"
    "\n"
    "uniform mat4 projection;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = projection * vec4(a_pos, 0.0, 1.0);\n"
    "\n"
    "    f_color = a_color;\n"
    "    f_tex_coord = a_tex_coord;\n"
    "}\n";

const char* UI_FONT_FRAGMENT_SHADER = 
    "#version 300 es\n"
    "\n"
    "precision mediump float;\n"
    "\n"
    "in vec4 f_color;\n"
    "in vec2 f_tex_coord;\n"
    "\n"
    "out vec4 FragColor;\n"
    "\n"
    "uniform sampler2D sampler;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 sampled = vec4(1.0, 1.0, 1.0, texture(sampler, f_tex_coord).r);\n"
    "    FragColor = f_color * sampled;\n"
    "}\n";
