#pragma once

#include <cglm/struct.h>

// TODO: Implement MOD KEYS

typedef enum
{
	INPUT_KEY_UNKNOWN = 0,
	INPUT_KEY_SPACE,
	INPUT_KEY_APOSTROPHE,
	INPUT_KEY_COMMA,
	INPUT_KEY_MINUS,
	INPUT_KEY_PERIOD,
	INPUT_KEY_SLASH,
	INPUT_KEY_0,
	INPUT_KEY_1,
	INPUT_KEY_2,
	INPUT_KEY_3,
	INPUT_KEY_4,
	INPUT_KEY_5,
	INPUT_KEY_6,
	INPUT_KEY_7,
	INPUT_KEY_8,
	INPUT_KEY_9,
	INPUT_KEY_SEMICOLON,
	INPUT_KEY_EQUAL,
	INPUT_KEY_A,
	INPUT_KEY_B,
	INPUT_KEY_C,
	INPUT_KEY_D,
	INPUT_KEY_E,
	INPUT_KEY_F,
	INPUT_KEY_G,
	INPUT_KEY_H,
	INPUT_KEY_I,
	INPUT_KEY_J,
	INPUT_KEY_K,
	INPUT_KEY_L,
	INPUT_KEY_M,
	INPUT_KEY_N,
	INPUT_KEY_O,
	INPUT_KEY_P,
	INPUT_KEY_Q,
	INPUT_KEY_R,
	INPUT_KEY_S,
	INPUT_KEY_T,
	INPUT_KEY_U,
	INPUT_KEY_V,
	INPUT_KEY_W,
	INPUT_KEY_X,
	INPUT_KEY_Y,
	INPUT_KEY_Z,
	INPUT_KEY_LEFT_BRACKET,
	INPUT_KEY_BACKSLASH,
	INPUT_KEY_RIGHT_BRACKET,
	INPUT_KEY_GRAVE_ACCENT,
	INPUT_KEY_WORLD_1,
	INPUT_KEY_WORLD_2,
	INPUT_KEY_ESCAPE,
	INPUT_KEY_ENTER,
	INPUT_KEY_TAB,
	INPUT_KEY_BACKSPACE,
	INPUT_KEY_INSERT,
	INPUT_KEY_DELETE,
	INPUT_KEY_RIGHT,
	INPUT_KEY_LEFT,
	INPUT_KEY_DOWN,
	INPUT_KEY_UP,
	INPUT_KEY_PAGE_UP,
	INPUT_KEY_PAGE_DOWN,
	INPUT_KEY_HOME,
	INPUT_KEY_END,
	INPUT_KEY_CAPS_LOCK,
	INPUT_KEY_SCROLL_LOCK,
	INPUT_KEY_NUM_LOCK,
	INPUT_KEY_PRINT_SCREEN,
	INPUT_KEY_PAUSE,
	INPUT_KEY_F1,
	INPUT_KEY_F2,
	INPUT_KEY_F3,
	INPUT_KEY_F4,
	INPUT_KEY_F5,
	INPUT_KEY_F6,
	INPUT_KEY_F7,
	INPUT_KEY_F8,
	INPUT_KEY_F9,
	INPUT_KEY_F10,
	INPUT_KEY_F11,
	INPUT_KEY_F12,
	INPUT_KEY_F13,
	INPUT_KEY_F14,
	INPUT_KEY_F15,
	INPUT_KEY_F16,
	INPUT_KEY_KP_0,
	INPUT_KEY_KP_1,
	INPUT_KEY_KP_2,
	INPUT_KEY_KP_3,
	INPUT_KEY_KP_4,
	INPUT_KEY_KP_5,
	INPUT_KEY_KP_6,
	INPUT_KEY_KP_7,
	INPUT_KEY_KP_8,
	INPUT_KEY_KP_9,
	INPUT_KEY_KP_DECIMAL,
	INPUT_KEY_KP_DIVIDE,
	INPUT_KEY_KP_MULTIPLY,
	INPUT_KEY_KP_SUBTRACT,
	INPUT_KEY_KP_ADD,
	INPUT_KEY_KP_ENTER,
	INPUT_KEY_KP_EQUAL,
	INPUT_KEY_LEFT_SHIFT,
	INPUT_KEY_LEFT_CONTROL,
	INPUT_KEY_LEFT_ALT,
	INPUT_KEY_LEFT_SUPER,
	INPUT_KEY_RIGHT_SHIFT,
	INPUT_KEY_RIGHT_CONTROL,
	INPUT_KEY_RIGHT_ALT,
	INPUT_KEY_RIGHT_SUPER,
	INPUT_KEY_MENU,

	INPUT_KEY_LAST = INPUT_KEY_MENU,

	INPUT_KEY_COUNT,
} InputKey;

typedef enum 
{
	INPUT_MOUSE_BUTTON_UNKNOWN = 0,
	INPUT_MOUSE_BUTTON_1,
	INPUT_MOUSE_BUTTON_2,
	INPUT_MOUSE_BUTTON_3,
	INPUT_MOUSE_BUTTON_4,
	INPUT_MOUSE_BUTTON_5,
	INPUT_MOUSE_BUTTON_6,
	INPUT_MOUSE_BUTTON_7,
	INPUT_MOUSE_BUTTON_8,

	INPUT_MOUSE_BUTTON_LEFT = INPUT_MOUSE_BUTTON_1,
	INPUT_MOUSE_BUTTON_RIGHT = INPUT_MOUSE_BUTTON_2,
	INPUT_MOUSE_BUTTON_MIDDLE = INPUT_MOUSE_BUTTON_3,
	INPUT_MOUSE_BUTTON_LAST = INPUT_MOUSE_BUTTON_8,

	INPUT_MOUSE_BUTTON_COUNT = INPUT_MOUSE_BUTTON_LAST+1,
} InputMouseButton;

typedef struct
{
	bool left;
	bool right;
	bool forward;
	bool backward;
	bool up;
	bool down;
} InputState;


bool window_input_key_is_down(InputKey key);
bool window_input_key_just_pressed(InputKey key);
bool window_input_key_just_released(InputKey key);

bool window_input_mouse_btn_is_down(InputMouseButton btn);
bool window_input_mouse_btn_just_pressed(InputMouseButton btn);
bool window_input_mouse_btn_just_released(InputMouseButton btn);
vec2s window_input_mouse_get_position();
vec2s window_input_mouse_get_scroll();
bool window_input_mouse_has_moved();
